sudo: false
install: true
language: node_js
install:
    - pip install --user awscli
node_js: 
    - "8"
env:
    global:
        # include $HOME/.local/bin for `aws`
        - PATH=$HOME/.local/bin:$PATH
    matrix:
        - TEST_SUITE=short-tests
        - TEST_SUITE=long-tests
        - TEST_SUITE=lint
script:
    make -j2 ${TEST_SUITE}

jobs:
    include:
        - stage: deploy
          if: branch = master and type != pull_request
          env: TEST_SUITE=upload
