sudo: false
language: node_js
install:
  - pip install --user awscli
node_js:
  - '12'
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    # GH_TOKEN=<secret> maps to ecb...ca5
    - secure: iSv2VWrSWlGERo6jl6V2SLwfWPxx/Y54jTyXBOQLz/nhuzHYFmzvCxNQ9uZkbPC+cQwopcWsxAM+rgWsOJtGiKay2hIJ9qBHknHcSlKaRwiA+2fr8ljTe52kHW3HY6IDj1PyCX7JDG7xFIhYP+URDF3eO9W5XxowIP5d2VP6GGI=
cache:
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"
    - "$HOME/.npm/_prebuilds"
jobs:
  include:
    - name: Short tests
      script: make -j2 short-tests
    - name: Long tests
      script: make -j2 long-tests
    - name: Lint
      script: make -j2 lint
    - stage: deploy
      name: Website
      if: branch = master and type != pull_request
      script: make -j2 upload
    - stage: deploy
      name: Electron Windows & Mac
      os: osx
      osx_image: xcode11.4
      script:
        - npm install
        - npm run release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: deploy
      name: Linux
      os: linux
      dist: trusty
      script:
        - npm install
        - npm run release
